development:
  adapter: postgresql
  encoding: unicode
  database: photo_albums_development
  pool: 15
  username: photo_albums

test:
  adapter: postgresql
  encoding: unicode
  database: photo_albums_test
  pool: 15
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: photo_albums_production
  pool: 15
  username: photo_albums
  password:
